py_shop/py_shop/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('shop.base_url')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

py_shop/shop/models.py
from django.db import models
from autoslug import AutoSlugField
from django.urls import reverse
from decimal import Decimal
from django.conf import settings
import string
import random

def image_folder(instance, filename):
    '''This is func load correct url_name image'''
    filename = instance.slug + '.' + filename.split('.')[1]
    return f'{instance.slug}/{filename}'


class ThemeFront(models.Model):

    title = models.CharField(max_length=120)
    slug = AutoSlugField(populate_from='title')
    image = models.ImageField(upload_to=image_folder)

    def __str__(self):
        return self.title


class Category(models.Model):

    name = models.CharField(max_length=100)
    slug = AutoSlugField(populate_from='name')
    image = models.ImageField(upload_to=image_folder, blank=True)
    priority = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category_detail', kwargs={'category_slug': self.slug})


class Brand(models.Model):

    name = models.CharField(max_length=100)
    slug = AutoSlugField(populate_from='name')
    image = models.ImageField(upload_to=image_folder, blank=True)
    priority = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('brand_detail', kwargs={'brand_slug': self.slug})


class Product(models.Model):

    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    title = models.CharField(max_length=120, db_index=True)
    slug = AutoSlugField(populate_from='title', db_index=True)
    image = models.ImageField(upload_to=image_folder, blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=11, decimal_places=2)
    available = models.BooleanField(default=True, verbose_name='В наличии')
    stock = models.PositiveIntegerField(verbose_name='На складе')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    priority = models.BooleanField(default=False)

    class Meta:
        ordering = ['title']
        index_together = [
            ['id', 'slug']
        ]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('product_detail', kwargs={'product_slug': self.slug})


class Info(models.Model):

    title = models.CharField(max_length=100)
    slug = AutoSlugField(populate_from='title')
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to=image_folder, blank=True)
    priority = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('info_detail', kwargs={'info_slug': self.slug})


class Asker(models.Model):

    title = models.CharField(max_length=100)
    slug = AutoSlugField(populate_from='title')
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to=image_folder, blank=True)
    priority = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('asker_detail', kwargs={'asker_slug': self.slug})


class CartItem(models.Model):

    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    qty = models.PositiveIntegerField(default=1)
    item_total = models.DecimalField(max_digits=12, decimal_places=2, default=0.00)

    def __str__(self):
        return f'Корзина для товара {self.product.title}'


class Cart(models.Model):

    items = models.ManyToManyField(CartItem, blank=True)
    cart_total = models.DecimalField(max_digits=12, decimal_places=2, default=0.00)

    def __str__(self):
        return str(self.id)

    def add_to_cart_mod(self, product_slug):
        cart = self
        product = Product.objects.get(slug=product_slug)
        new_item, _ = CartItem.objects.get_or_create(product=product, item_total=product.price)
        if new_item not in cart.items.all():
            cart.items.add(new_item)
            cart.save()

    def remove_from_cart_mod(self, product_slug):
        cart = self
        product = Product.objects.get(slug=product_slug)
        for cart_item in cart.items.all():
            if cart_item.product == product:
                cart.items.remove(cart_item)
                cart.save()

    def count_qty(self, qty, item_id):
        cart = self
        cart_item = CartItem.objects.get(id=int(item_id))
        cart_item.qty = int(qty)
        cart_item.item_total = int(qty) * Decimal(cart_item.product.price)
        cart_item.save()
        value_cart_total = 0.00
        for item in cart.items.all():
            value_cart_total += float(item.item_total)
        cart.cart_total = value_cart_total
        cart.save()


ORDER_STATUS_CHOICES = (
    ("Принят в обработку", "Принят в обработку"),
    ("Выполняется", "Выполняется"),
    ("Оплачен", "Оплачен"),
)


def generate_string():
    unique = [i for i in string.ascii_lowercase] + [str(i) for i in range(10)]
    random.shuffle(unique)
    unique_url = ''.join([random.choice(unique) for i in range(10)])
    return unique_url


unique_slug = generate_string()


class Order(models.Model):

    global unique_slug
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    items = models.ManyToManyField(Cart)
    total = models.DecimalField(max_digits=9, decimal_places=2, default=0.00)
    first_name = models.CharField(max_length=120)
    last_name = models.CharField(max_length=120)
    phone = models.CharField(max_length=13)
    address = models.CharField(max_length=120)
    buying_type = models.CharField(max_length=40, choices=(("Самовывоз", "Самовывоз"),
                                                           ("Доставка", "Доставка")), default="Доставка")
    sail = models.CharField(max_length=40, choices=(("Наличными", "Наличными"),
                                                    ("Картой", "Картой")), default="Наличными")
    date = models.DateTimeField(auto_now_add=True)
    date_delivery = models.CharField(max_length=40, blank=True)
    comment = models.TextField(blank=True)
    status = models.CharField(max_length=120, choices=ORDER_STATUS_CHOICES, default="Принят в обработку")

    def __str__(self):
        return f"Заказ под номером {str(self.id)}"

py_shop/shop/views.py
from django.shortcuts import render
from shop.models import ThemeFront, Product, Category, Info, Asker, Brand, Cart, CartItem, Order
from django.http import JsonResponse, HttpResponseRedirect
from shop.form import OrderForm, RegistrationForm, LoginForm
from django.urls import reverse
from django.contrib.auth import login, authenticate


infos = Info.objects.all()
askers = Asker.objects.filter(priority=True)
inf_infs = Asker.objects.filter(priority=False)
brands = Brand.objects.filter(priority=True)
context_1 = {
    'infos': infos,
    'askers': askers,
    'inf_infs': inf_infs,
    'brands': brands,
}


def base_view(request):
    '''Base page'''
    categories = Category.objects.filter(priority=True)
    products = Product.objects.filter(priority=True)
    images = ThemeFront.objects.all()
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    context = {
        'categories': categories,
        'products': products,
        'images': images,
        'cart': cart,
    }
    context = {**context, **context_1}
    return render(request, 'base.html', context=context)


def product_view(request, product_slug):
    '''Page of product'''
    product = Product.objects.get(slug=product_slug)
    categories = Category.objects.filter(priority=True)
    products = Product.objects.all()
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    context = {
        'products': products,
        'product': product,
        'categories': categories,
        'cart': cart,
    }
    context = {**context, **context_1}
    return render(request, 'product.html', context=context)


def category_view(request, category_slug):
    '''Single category pages'''
    category = Category.objects.get(slug=category_slug)
    product_of_category = Product.objects.filter(category=category)
    products = Product.objects.all()
    categories = Category.objects.filter(priority=True)
    categories_all = Category.objects.all()
    category_title = Category.objects.get(slug=category_slug)
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    context = {
        'product_of_category': product_of_category,
        'categories_all': categories_all,
        'categories': categories,
        'products': products,
        'cart': cart,
        'category_title': category_title,
    }
    context = {**context, **context_1}
    return render(request, 'category.html', context=context)


def category_all_view(request):
    '''Page of all catefories'''
    categories = Category.objects.all()
    cart = Cart.objects.first()
    context = {
        'categories': categories,
        'cart': cart,
    }
    context = {**context, **context_1}
    return render(request, 'category_ever.html', context=context)


def brand_view(request):
    '''Single brand pages'''
    categories = Category.objects.filter(priority=True)
    brands_all = Brand.objects.all()
    cart = Cart.objects.first()
    context = {
        'categories': categories,
        'brands_all': brands_all,
        'cart': cart,
    }
    context = {**context, **context_1}
    return render(request, 'brands.html', context=context)


def brand_one_view(request, brand_slug):
    '''Page of all brands'''
    brand = Brand.objects.get(slug=brand_slug)
    product_of_brand = Product.objects.filter(brand=brand)
    categories = Category.objects.filter(priority=True)
    brand_title = Brand.objects.get(slug=brand_slug)
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    context = {
        'product_of_brand': product_of_brand,
        'categories': categories,
        'cart': cart,
        'brand_title': brand_title,
    }
    context = {**context, **context_1}
    return render(request, 'brand_one.html', context=context)


def repairs_view(request):
    '''Info (service)'''
    categories = Category.objects.filter(priority=True)
    cart = Cart.objects.first()
    context = {
        'categories': categories,
        'cart': cart,
    }
    context = {**context, **context_1}
    return render(request, 'repairs.html', context=context)


def asker_view_one(request):
    '''Info (askers(1))'''
    categories = Category.objects.filter(priority=True)
    cart = Cart.objects.first()
    context = {
        'categories': categories,
        'cart': cart,
    }
    context = {**context, **context_1}
    return render(request, 'asker_1.html', context=context)


def asker_view_two(request):
    '''Info (askers(2))'''
    categories = Category.objects.filter(priority=True)
    cart = Cart.objects.first()
    context = {
        'categories': categories,
        'cart': cart,
    }
    context = {**context, **context_1}
    return render(request, 'asker_2.html', context=context)


def target_view(request):
    '''Info (about website)'''
    categories = Category.objects.filter(priority=True)
    cart = Cart.objects.first()
    context = {
        'categories': categories,
        'cart': cart,
    }
    context = {**context, **context_1}
    return render(request, 'target.html', context=context)


def history_orders_view(request):
    '''History orders'''
    categories = Category.objects.filter(priority=True)
    cart = Cart.objects.first()
    if request.user.is_active:
        order = Order.objects.filter(user=request.user).order_by('id')
        context = {
            'categories': categories,
            'cart': cart,
            'order': order,
        }
        context = {**context, **context_1}
        return render(request, 'history_orders.html', context=context)
    context = {
        'categories': categories,
        'cart': cart,
    }
    context = {**context, **context_1}
    return render(request, 'history_orders.html', context=context)


def cart_base_view(request):
    '''Base page if cart'''
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    categories = Category.objects.filter(priority=True)
    context = {
        'cart': cart,
        'categories': categories,
    }
    context = {**context, **context_1}
    return render(request, 'cart.html', context=context)


def add_to_cart(request):
    '''Add product in cart'''
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    product_slug = request.GET.get('product_slug')
    product = Product.objects.get(slug=product_slug)
    cart.add_to_cart_mod(product.slug)
    value_cart_total = 0.00
    for item in cart.items.all():
        value_cart_total += float(item.item_total)
    cart.cart_total = value_cart_total
    cart.save()
    return JsonResponse(
        {
            'cart_total': cart.items.count(),
            'cart_total_final': cart.cart_total,
        }
    )


def remove_from_cart(request):
    '''Delete product from cart'''
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    product_slug = request.GET.get('product_slug')
    product = Product.objects.get(slug=product_slug)
    cart.remove_from_cart_mod(product.slug)
    value_cart_total = 0.00
    for item in cart.items.all():
        value_cart_total += float(item.item_total)
    cart.cart_total = value_cart_total
    cart.save()
    return JsonResponse(
        {
            'cart_total': cart.items.count(),
            'cart_total_final': cart.cart_total,
        }
    )


def count_item_qty(request):
    '''Sum total and price on cart'''
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    qty = request.GET.get('qty')
    item_id = request.GET.get('item_id')
    cart_item = CartItem.objects.get(id=int(item_id))
    cart.count_qty(qty, item_id)
    return JsonResponse(
        {
            'cart_total': cart.items.count(),
            'item_total_final': cart_item.item_total,
            'cart_total_final': cart.cart_total,
        }
    )


def checkout_view(request):
    '''Page pre order'''
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:

py_shop/shop/templates/asker_1.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<script src="{% static 'js/jquery.min.js' %}"></script>
{% endblock content %}

py_shop/shop/templates/asker_2.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<script src="{% static 'js/jquery.min.js' %}"></script>
{% endblock content %}

py_shop/shop/templates/brand_one.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<script src="{% static 'js/jquery.min.js' %}"></script>
<div class="col-sm-12">
    <h1 class="text-center">{{ brand_title.name }}</h1>
    <hr>
    {% for product in product_of_brand %}


    <div class="col-sm-4 col-lg-4 col-md-4" >
        <div class="thumbnail">
            <img src="{{ product.image.url }}" alt="" style='width:auto; height:250px;'>
            <div class="caption">
                <h4 class="pull-right">{{ product.price}} руб</h4>
                <h5>
                    <strong>
                        <a href="{{ product.get_absolute_url }}">{{ product.title }}</a>
                    </strong>
                </h5>
                <style type="text/css">
                    p.clip {
                    white-space: nowrap;
                    overflow: hidden;
                    padding: 10px;
                    text-overflow: ellipsis;
                    }
                </style>
                <p class="clip">{{ product.description}}</p>
            </div>
            <p class="text-center">
                {% if not request.user.is_authenticated %}
            <p class="text-center" style="font-size:15px">Чтобы добавить товар, нужно
                <a target="_blank" href="{% url 'login' %}">войти</a> или
                <a target="_blank" href="{% url 'registration' %}">зарегестрироваться</a>
            </p>
            {% else %}
            <a href="#" class='add_to_cart' data-slug='{{ product.slug }}' class="text-center">
                <button class="btn-success">Добавить в корзину</button>
            </a>
            {% endif %}
            </p>
            <div class="ratings">
                <p class="pull-right">15 reviews</p>
                <p>
                    <span class="glyphicon glyphicon-star"></span>
                    <span class="glyphicon glyphicon-star"></span>
                    <span class="glyphicon glyphicon-star"></span>
                    <span class="glyphicon glyphicon-star"></span>
                    <span class="glyphicon glyphicon-star"></span>
                </p>
            </div>
        </div>
    </div>
    <script>
    $(document).ready(function(){
        $('.add_to_cart').on('click', function(e){
            e.preventDefault()
            product_slug = $(this).attr('data-slug')
            data = {
                product_slug : product_slug
            }
            $.ajax({
                type: "GET",
                url:"{% url 'add_to_cart' %}",
                data: data,
                success: function(data){
                    $("#cart_count").html(data.cart_total)
                }
            })
        })
    })
    </script>
    {% endfor %}
</div>
{% endblock content %}

py_shop/shop/templates/brands.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<script src="{% static 'js/jquery.min.js' %}"></script>
<h1 class="text-center">Все бренды</h1>
<hr>
<div class="row">
    {% for brand in brands_all %}
    <div class="col-sm-4 col-lg-4 col-md-4">
        <div class="thumbnail">
            <img src="{{ brand.image.url }}" alt="" style='width:auto; height:250px;'>
            <div class="caption">
                <h5>
                    <strong>
                        <hr>
                        <p class=" lead text-center">
                            <a href="{{ brand.get_absolute_url }}" class="text-center">{{ brand.name }}</a>
                        </p>
                    </strong>
                </h5>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock content %}

py_shop/shop/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<script src="{% static 'js/jquery.min.js' %}"></script>
{% if cart.items.count > 0 %}
<style type="text/css">
    table {
      border: none;
    }
</style>
<div class="my-cart">
    <h1 class="text-center">Корзина</h1>
<table class="table" style="font-size:17px" border="2px" bgcolor="#89EC6A" align="center">
    <thead>
    <tr>
        <th>Изображение</th>
        <th>Товар</th>
        <th>Колл-во</th>
        <th>Цена</th>
        <th>Итоговая цена</th>
        <th>Удалить</th>
    </tr>
    </thead>
        <tbody>
        {% for item in cart.items.all %}
           <tr class="cart-item-{{ item.product.id }}">
                <td class="text-center">
                    <img src="{{ item.product.image.url }}" alt="" style='padding-left:auto; height:30%;'/>
                </td>
                <td class="text-left">
                    <a  href="{{ item.product.get_absolute_url }}">{{ item.product.title }}</a>
                </td>
                <td class="text-center">
                    <form action="" method="GET">
                         <input type="number" name="qty" class="cart-item-qty"
                                data-id="{{ item.id }}" value="{{ item.qty }}" min='1' max="25" style="width: 50px;">
                    </form>
                </td>
                <td class="text-left">{{ item.item_total }} руб.</td>
                <td class='text-center' id="cart-item-total-{{ item.id }}">{{ item.item_total }} руб.</td>
                <td>
                    <a href="#" class='remove_from_cart' data-slug="{{ item.product.slug }}" data-id="{{ item.product.id }}" >
                        <button class="btn-danger">Удалить</button>
                    </a>
                </td>
           </tr>
        {% endfor %}
        <tr class="total" style="font-size:20px">
            <td class='text-center'><h3>Всего к оплатe:</h3></td>
            <td colspan="4"></td>
            <td class="num" id="cart-total-price">{{ cart.cart_total }} руб.</td>
        </tr>
        </tbody>
</table>
    <br>
    <a href="{% url 'checkout' %}" class="pull-right" style="font-size:17px">
        <button class="btn btn-success">Оформить заказ</button>
    </a>
</div>
    <h1 class="cart-empty"></h1>
    <h3 class="cart-empty-t"></h3>
{% else %}
    <h1 class="text-center">Ваша корзина пуста</h1>
    <h3 class='text-right'>Всего к оплатe: 0 руб.</h3>
{% endif %}
<script>
    $(document).ready(function(){
        $('.remove_from_cart').on('click', function(e){
            e.preventDefault()
            product_slug = $(this).attr('data-slug')
            item_product_id = $(this).attr('data-id')
            data = {
                product_slug : product_slug
            }
            $.ajax({
                type: "GET",
                url:"{% url 'remove_from_cart' %}",
                data: data,
                success: function(data){
                    $("#cart_count").html(data.cart_total)
                    $(".cart-item-"+item_product_id).css('display', 'none')
                    $("#cart-total-price").html(parseFloat(data.cart_total_final).toFixed(2) + 'руб.')
                    if (parseInt(data.cart_total) == 0){
                        $('.my-cart').css('display', 'none')
                        $('.cart-empty').html('<h1 class="text-center">Ваша корзина пуста</h1>')
                        $('.cart-empty-t').html('<h3 class="text-right">Всего к оплатe: 0 руб.</h3>')
                    }
                }
            })
        })
    })
    $(document).ready(function(){
        $('.cart-item-qty').on('click', function(){
            qty = $(this).val()
            item_id = $(this).attr('data-id')
            data = {
                qty: qty,
                item_id: item_id
            }
            $.ajax({
                type: "GET",
                url: "{% url 'count_item_qty' %}",
                data: data,
                success: function(data){
                    $("#cart-item-total-" + item_id).html(parseFloat(data.item_total_final).toFixed(2) + 'руб.')
                    $("#cart-total-price").html(parseFloat(data.cart_total_final).toFixed(2) + 'руб.')
                }
            })
        })
    })
</script>
{% endblock content %}

py_shop/shop/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<script src="{% static 'js/jquery.min.js' %}"></script>
<div class="col-sm-12">
    <h1 class="text-center">{{ category_title.name }}</h1>
    <hr>
    {% for product in product_of_category %}
    <div class="col-sm-4 col-lg-4 col-md-4" >
        <div class="thumbnail">
            <img src="{{ product.image.url }}" alt="" style='width:auto; height:250px;'>
            <div class="caption">
                <h4 class="pull-right">{{ product.price}} руб</h4>
                <h5>
                    <strong>
                        <a href="{{ product.get_absolute_url }}">{{ product.title }}</a>
                    </strong>
                </h5>
                <style type="text/css">
                    p.clip {
                    white-space: nowrap;
                    overflow: hidden;
                    padding: 10px;
                    text-overflow: ellipsis;
                    }
                </style>
                <p class="clip">{{ product.description}}</p>
            </div>
            <p class="text-center">
                {% if not request.user.is_authenticated %}
            <p class="text-center" style="font-size:15px">Чтобы добавить товар, нужно
                <a target="_blank" href="{% url 'login' %}">войти</a> или
                <a target="_blank" href="{% url 'registration' %}">зарегестрироваться</a>
            </p>
            {% else %}
            <a href="#" class='add_to_cart' data-slug='{{ product.slug }}' class="text-center">
                <button class="btn-success">Добавить в корзину</button>
            </a>
            {% endif %}
            </p>
            <div class="ratings">
                <p class="pull-right">15 reviews</p>
                <p>
                    <span class="glyphicon glyphicon-star"></span>
                    <span class="glyphicon glyphicon-star"></span>
                    <span class="glyphicon glyphicon-star"></span>
                    <span class="glyphicon glyphicon-star"></span>
                    <span class="glyphicon glyphicon-star"></span>
                </p>
            </div>
        </div>
    </div>
    <script>
    $(document).ready(function(){
        $('.add_to_cart').on('click', function(e){
            e.preventDefault()
            product_slug = $(this).attr('data-slug')
            data = {
                product_slug : product_slug
            }
            $.ajax({
                type: "GET",
                url:"{% url 'add_to_cart' %}",
                data: data,
                success: function(data){
                    $("#cart_count").html(data.cart_total)
                }
            })
        })
    })
    </script>
    {% endfor %}
</div>
{% endblock content %}

py_shop/shop/templates/category_ever.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<script src="{% static 'js/jquery.min.js' %}"></script>
<h1 class="text-center">Все категории</h1>
<hr>
<div class="row">
    {% for category in categories %}
    <div class="col-sm-4 col-lg-4 col-md-4">
        <div class="thumbnail">
            <img src="{{ category.image.url }}" alt="" style='width:auto; height:250px;'>
            <div class="caption">
                <h5>
                    <strong>
                        <hr>
                        <p class=" lead text-center">
                            <a href="{{ category.get_absolute_url }}" class="text-center">{{ category.name }}</a>
                        </p>
                    </strong>
                </h5>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock content %}

py_shop/shop/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<script src="{% static 'js/jquery.min.js' %}"></script>
<h3 class="text-center">Авторизация</h3>
<div class="col-sm-8 col-sm-offset-2">
<form action='' method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="col-sm-4 col-sm-offset-8">
        <input type="submit" class="btn btn-success btn-block" style="font-size:18px" value="Войти">
    </div>
</form>
</div>
{% endblock content %}

py_shop/shop/templates/order.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<script src="{% static 'js/jquery.min.js' %}"></script>
<br>
<style type="text/css">
    table {
      border: none;
    }
</style>
<form action='{% url "thank_you" %}' method="POST">
    {% csrf_token %}
    <div class="col-sm-4">
        {{ form.name|as_crispy_field }}
        {{ form.sail|as_crispy_field }}
    </div>
    <div class="col-sm-4">
        {{ form.last_name|as_crispy_field }}
        {{ form.buying_type|as_crispy_field }}
    </div>
    <div class="col-sm-4">
        {{ form.phone|as_crispy_field }}
        {{ form.address_true|as_crispy_field }}
    </div>
    <div class="col-sm-4">
        {{ form.date_delivery|as_crispy_field }}
    </div>
    <div class="col-sm-8">
        {{ form.comment|as_crispy_field }}
        <a href="#" class="pull-right" style="font-size:20px">
            <button class="btn-success">Готово</button>
        </a>
    </div>
</form>
<script>
    $(document).ready(function(){
        $('#id_buying_type').on('click', function(){
            buying_type = $(this).val()
            if (buying_type == 'Доставка'){
                $('#div_id_address_true').css('display', 'block')
                $('#div_id_date_delivery').css('display', 'block')
            }else{
                $('#div_id_address_true').css('display', 'none')
                $('#div_id_date_delivery').css('display', 'none')
            }
        })
    })
</script>
{% endblock content %}

py_shop/shop/templates/registration.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<script src="{% static 'js/jquery.min.js' %}"></script>
<h3 class="text-center">Регистрация нового пользователя</h3>
<div class="col-sm-8 col-sm-offset-2">
<form action='' method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="col-sm-4 col-sm-offset-8">
        <input type="submit" class="btn btn-success btn-block" value="Зарегистрировать">
    </div>
</form>
</div>

{% endblock content %}

py_shop/shop/templates/target.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<script src="{% static 'js/jquery.min.js' %}"></script>
{% endblock content %}